name: Deploy Backend to EC2 with CodeDeploy

on:
  workflow_dispatch: # 수동 실행
  push:
    branches:
      - deploy-backend # deploy-backend 브랜치에 push할 때만 자동 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Prepare deploy package
        run: |
          mkdir -p deploy
          cp backend/build/libs/*.jar deploy/
          cp appspec.yml deploy/
          cp backend/deploy.sh deploy/
          cd deploy && zip -r deploy.zip .

      - name: Upload to S3 (for CodeDeploy)
        uses: aws-actions/s3-sync@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          source: deploy/
          destination: s3://your-codedeploy-bucket-name/library-backend/
          delete: false

      - name: Deploy via CodeDeploy
        uses: aws-actions/aws-codedeploy@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          application-name: LibraryApp
          deployment-group: LibraryGroup
          bundle-type: zip
          bucket: your-codedeploy-bucket-name
          key: library-backend/deploy.zip
